### PR TITLE
Create index.js

### PR DESCRIPTION
**Pull request by mahdid-lilia**

### CODE REVIEW

**Comment by akram09** [comment]
Hey, @mahdid-lilia thank you for the contribution, just have one question I'm sorry I didn't quite understand what is the `index.js` used for?

**Comment by mahdid-lilia** [comment]
Hello @akram09, thank you for your response, just last time I had a problem while submitting my contribution so I created another file index.js and I put the changes made in it, otherwise it's the same one that is in the project named "index.ts" in the src folder (I am sorry I should have given it the same name).

**Comment by abdelghanimeliani** [comment]
Hey, @mahdid-lilia thank you for the contribution again ,I just tested your pull request the project still work , I just want to know if the changes are just corrections of spelling errors or  you have other changes that you haven't pushed yet ?

**Comment by abdelghanimeliani** [comment]
hey again  @mahdid-lilia after reviewing your code again  we concluded that not legitemate it don't improve the current work , but we have decided to merge it taking into consideration that's this is your first request with us , thank you angain

**Pull request merged**
